'use strict'

module.exports = {
  INSUFFICIENT_ARGS_EVENT: 'INSUFFICIENT_ARGS_EVENT',
  INSUFFICIENT_ARGS_EVENT_BODY: 'INSUFFICIENT_ARGS_EVENT_BODY',
  INVALID_ARGS_EVENT: 'INVALID_ARGS_EVENT',
  INSUFFICIENT_ARGS_SUBSCRIPTION_ID: 'INSUFFICIENT_ARGS_SUBSCRIPTION_ID',
  INSUFFICIENT_ARGS_PLAN_ID: 'INSUFFICIENT_ARGS_PLAN_ID',
  INSUFFICIENT_ARGS_PLAN_NAME: 'INSUFFICIENT_ARGS_PLAN_NAME',
  INSUFFICIENT_ARGS_STRIPE_TOKEN: 'INSUFFICIENT_ARGS_STRIPE_TOKEN',
  INSUFFICIENT_ARGS_STRIPE_EMAIL: 'INSUFFICIENT_ARGS_STRIPE_EMAIL',

  ACCOUNT_CREATION_UNSUCCESSFUL: 'ACCOUNT_CREATION_UNSUCCESSFUL',
  SUBSCRIPTION_CREATION_UNSUCCESSFUL: 'SUBSCRIPTION_CREATION_UNSUCCESSFUL'
}
